logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: INFO
    com.example.demo.controller: INFO
  file:
    name: logs/application-debug.log

backend:
  server:
    http://localhost
  port:
    8080